version: "3.7"

networks:
  kafka-network:
    driver: bridge

services:
  postgres:
    image: "postgres:15.1"
    container_name: "postgres"
    hostname: postgres
    networks:
      - kafka-network
    ports:
      - "5432:5432"
    volumes:
      - ./dbs-init.sql:/docker-entrypoint-initdb.d/dbs-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=demo
